---
title: "Data Wrangling"
author: "Larry Alade"
date: "October 22, 2018"
output: html_document
---

```{r}
library(tidyverse) # install.packages("tidyverse")
```
## load and inspect dataset
```{r}
## read gapminder csv. Note the readr:: prefix identifies which package it's in
gapminder <- readr::read_csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv')
head(gapminder) # GIVES YOU THE FIRST SIX RECORDS BY DEFAULT
View(gapminder)
tail(gapminder) # list bottom six records by default
head(gapminder,3) # define number of records
str(gapminder)
summary(gapminder)


#Sidebar another way to look at summary data at a deeped level
install.packages("skimr")
skimr::skim(gapminder)

names(gapminder) #column names

dim(gapminder)
ncol(gapminder)
nrow(gapminder)

#reverse-engineer dim
c(nrow(gapminder), ncol (gapminder))


```

## Dplyr
```{r}
# filter by rows
filter(gapminder, lifeExp < 29)
filter(gapminder, country == "Mexico")
filter(gapminder, country %in% c("Mexico","Peru", "Brazil"))
filter(gapminder, country == "Mexico", year == 2002)

# find mean lifeExp of Sweden
sweden <- filter(gapminder, country == "Sweden")
names(sweden)
mean(sweden$lifeExp)

#select by columns
select(gapminder, year, lifeExp)
select(gapminder, -continent, -lifeExp)

#use select and filter together 
gap_cambodia <- filter(gapminder, country == "Cambodia")
gap_cambodia2 <- select(gap_cambodia, -continent, -lifeExp)

```

## The pipe operator will change your life
```{r}
gapminder %>% head()
gapminder %>% head(3)

## instead of this...
gap_cambodia  <- filter(gapminder, country == "Cambodia")
gap_cambodia2 <- select(gap_cambodia, -continent, -lifeExp) 

## ...we can do this
gap_cambodia  <- gapminder %>% 
  filter(country == "Cambodia")%>% 
  select(-continent, -lifeExp) 
```


##Mutate adds new variables
```{r}
gapminder%>%
  mutate((index = 1:nrow(gapminder)))

gapminder %>%
  mutate(planet = "Earth")

gapminder %>%
## Challenge Find max GdP of Eqgypt and Vietnam.  create a new column (I want just one number that is max of those countries.)

gapminder %>%  
filter(country %in% c("Vietnam", "Egypt")) %>%
  mutate (gdp = pop * gdpPercap) %>%
  mutate(max_gdp = max(gdp))

gapminder %>%  
filter(country %in% c("Vietnam", "Egypt")) %>%
  mutate (gdp = pop * gdpPercap,
          max_gdp = max(gdp))

```
























